language: go
go:
- 1.9
install: true
go_import_path: github.com/leonardojperez/prometheusTelemetry
env:
  global:
  - VERSION="${TRAVIS_BRANCH}_`date +%Y%m%d`_${TRAVIS_BUILD_NUMBER}"
before_script:
- go get -u gopkg.in/alecthomas/gometalinter.v2
- gometalinter.v2 --install &> /dev/null
script:
- make build